version: '3'
services:
    django:
        ports:
            - "8000:8000" 
        volumes:
            - ./youtube:/code
        build:
            context: ./youtube
            dockerfile: Dockerfile.django

    redis:
        image: redis
        restart: always

    worker:
        links:
            - redis
        depends_on:
            - redis
        volumes:
            - ./youtube:/code
        build:
            context: ./youtube
            dockerfile: Dockerfile.worker
