# Generated by Django 2.2.6 on 2021-06-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='discription',
            new_name='description',
        ),
    ]
