# Generated by Django 2.2.6 on 2021-06-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210611_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbernails',
        ),
    ]
