# Generated by Django 2.2.6 on 2021-06-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_thumbernail_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thumbernail',
            new_name='Thumbnail',
        ),
    ]
