FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /code/
CMD python manage.py makemigrations --merge --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000

