FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /code/
ENTRYPOINT celery -A youtube worker -l info
CMD python cronjob.py